"""initial tables

Revision ID: 6ec8a8d1f628
Revises: 
Create Date: 2026-02-24 18:50:02.987007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec8a8d1f628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_peso')
    op.drop_table('aplicacoes_vacina')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacoes_vacina',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vacina_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_aplicacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('proxima_dose', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], name=op.f('aplicacoes_vacina_animal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacina_id'], ['vacinas.id'], name=op.f('aplicacoes_vacina_vacina_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aplicacoes_vacina_pkey'))
    )
    op.create_table('registros_peso',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_registro', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], name=op.f('registros_peso_animal_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('registros_peso_pkey'))
    )
    # ### end Alembic commands ###
