"""initial tables

Revision ID: b93383719411
Revises: 
Create Date: 2026-02-24 18:14:07.627527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b93383719411'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplicacoes_vacina')
    op.drop_table('registros_peso')
    op.add_column('Alertas', sa.Column('data_resolucao', sa.DateTime(), nullable=False))
    op.add_column('Alertas', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.alter_column('Alertas', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('Alertas', 'animal_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('Alertas', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Alertas', 'mensagem',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Alertas', 'nivel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_Alertas_id'), 'Alertas', ['id'], unique=False)
    op.drop_constraint(op.f('Alertas_animal_id_fkey'), 'Alertas', type_='foreignkey')
    op.create_foreign_key(None, 'Alertas', 'animais', ['animal_id'], ['id'])
    op.drop_column('Alertas', 'data_criacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alertas', sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Alertas', type_='foreignkey')
    op.create_foreign_key(op.f('Alertas_animal_id_fkey'), 'Alertas', 'animais', ['animal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_Alertas_id'), table_name='Alertas')
    op.alter_column('Alertas', 'nivel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Alertas', 'mensagem',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Alertas', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Alertas', 'animal_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('Alertas', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('Alertas', 'criado_em')
    op.drop_column('Alertas', 'data_resolucao')
    op.create_table('registros_peso',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_registro', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], name=op.f('registros_peso_animal_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('registros_peso_pkey'))
    )
    op.create_table('aplicacoes_vacina',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vacina_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_aplicacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('proxima_dose', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], name=op.f('aplicacoes_vacina_animal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacina_id'], ['vacinas.id'], name=op.f('aplicacoes_vacina_vacina_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aplicacoes_vacina_pkey'))
    )
    # ### end Alembic commands ###
